# local_agent_setup_GBT_v.py

"""
This script outlines the structure of a local multi-agent system using Google's Agent Development Kit (ADK)
with locally hosted models. Each agent is specialized for a task in a collaborative coding environment.

This module can be run directly or imported by the multi_agent_ui.py for the web interface.
"""

import os
import json
import time
import logging
from datetime import datetime
from typing import Dict, List, Any, Optional

from adk.components import Agent, Sequential, Parallel, Loop, Tool
from adk.runtime import Context
from my_models import LocalModelWrapper
from system_monitor import get_monitor

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# === Tools ===
class SaveOutputTool(Tool):
    def run(self, input_data: str, context: Context) -> str:
        output_base_dir = "outputs"
        agent_logs_dir = os.path.join(output_base_dir, "agent_logs")
        src_dir = os.path.join(output_base_dir, "src")
        tests_dir = os.path.join(output_base_dir, "tests")

        os.makedirs(agent_logs_dir, exist_ok=True)
        os.makedirs(src_dir, exist_ok=True)
        os.makedirs(tests_dir, exist_ok=True)

        # Save agent logs
        for key in context.store_keys():
            if key.endswith("_output") or key in ["workflow_plan", "clarified_prompt"]:
                agent_name = key.replace("_output", "")
                log_path = os.path.join(agent_logs_dir, f"{agent_name}_log.txt")
                with open(log_path, "w") as f:
                    f.write(f"=== {agent_name.upper()} OUTPUT ===\n\n")
                    f.write(context.retrieve(key, f"No output for {agent_name}"))
                logger.info(f"Saved {agent_name} log to {log_path}")
        
        # Save final review
        final_output_log_path = os.path.join(agent_logs_dir, "final_processing_log.txt")
        with open(final_output_log_path, "w") as f:
            f.write("Reviewed Output/Final Summary:\n")
            f.write(context.retrieve("reviewed_output", "No reviewed output found."))
        
        # Create README.md
        readme_content = f"""# Project Output
## Generated by Multi-Agent System

**User Prompt:** {context.retrieve("user_prompt", "N/A")}
**Clarified Prompt:** {context.retrieve("clarified_prompt", "N/A")}

## Project Overview
{context.retrieve("workflow_plan", "No workflow plan available.")}

## Implementation Details
This project was generated by a collaborative multi-agent system with specialized agents:
- Orchestrator: Initial task understanding and clarification
- Workflow Designer: Task breakdown and planning
- Frontend Agent: UI and client-side implementation
- Backend Agent: Server-side and API implementation
- Reviewer: Code review and quality assurance

## Generated Files
- Source code: See the `src/` directory
- Tests: See the `tests/` directory
- Agent logs: See the `agent_logs/` directory

## Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""
        readme_path = os.path.join(output_base_dir, "README.md")
        with open(readme_path, "w") as f:
            f.write(readme_content)

        # Create architecture.json
        architecture_data = {
            "description": "High-level architecture of the generated solution",
            "user_prompt": context.retrieve("user_prompt", "N/A"),
            "clarified_prompt": context.retrieve("clarified_prompt", "N/A"),
            "workflow_plan": context.retrieve("workflow_plan", "N/A"),
            "agents_involved": [
                "OrchestratorAgent",
                "WorkflowDesignerAgent",
                "FrontendCodeAgent",
                "BackendCodeAgent",
                "ReviewerAgent"
            ],
            "outputs": {
                "log_file": final_output_log_path,
                "readme": readme_path,
                "source_directory": src_dir,
                "tests_directory": tests_dir
            },
            "generation_timestamp": datetime.now().isoformat()
        }
        architecture_path = os.path.join(output_base_dir, "architecture.json")
        with open(architecture_path, "w") as f:
            json.dump(architecture_data, f, indent=4)

        # Extract and save code files from agent outputs
        self._extract_and_save_code_files(context, src_dir, tests_dir)
        
        return f"Outputs saved. Main log: {final_output_log_path}. See all files in '{output_base_dir}'."
    
    def _extract_and_save_code_files(self, context: Context, src_dir: str, tests_dir: str):
        """Extract code blocks from agent outputs and save them as files."""
        # Process frontend output
        frontend_output = context.retrieve("frontend_output", "")
        self._extract_code_blocks(frontend_output, src_dir, "frontend")
        
        # Process backend output
        backend_output = context.retrieve("backend_output", "")
        self._extract_code_blocks(backend_output, src_dir, "backend")
        
        # Process reviewer output (might contain improved code)
        reviewer_output = context.retrieve("reviewed_output", "")
        self._extract_code_blocks(reviewer_output, src_dir, "improved")
    
    def _extract_code_blocks(self, text: str, output_dir: str, prefix: str):
        """Extract code blocks from text and save them as files."""
        import re
        
        # Find code blocks with filename hints
        # Pattern matches: ```language\n// filename: path/to/file.ext\ncode...```
        pattern = r"```(?:\w+)?\s*\n(?://|#)\s*filename:\s*([^\n]+)\n(.*?)```"
        matches = re.finditer(pattern, text, re.DOTALL)
        
        file_count = 0
        for match in enumerate(matches):
            file_count += 1
            filename = match[1].group(1).strip()
            code = match[1].group(2).strip()
            
            # Create subdirectories if needed
            file_path = os.path.join(output_dir, filename)
            os.makedirs(os.path.dirname(file_path), exist_ok=True)
            
            with open(file_path, "w") as f:
                f.write(code)
            logger.info(f"Saved code file: {file_path}")
        
        # If no filename hints were found, look for regular code blocks
        if file_count == 0:
            pattern = r"```(\w+)?\n(.*?)```"
            matches = re.finditer(pattern, text, re.DOTALL)
            
            for i, match in enumerate(matches):
                lang = match.group(1) or "txt"
                code = match.group(2).strip()
                
                # Generate a filename based on content or use a default
                if "class" in code and lang in ["python", "py"]:
                    # Try to extract class name
                    class_match = re.search(r"class\s+(\w+)", code)
                    if class_match:
                        filename = f"{class_match.group(1).lower()}.{lang}"
                    else:
                        filename = f"{prefix}_code_{i+1}.{lang}"
                elif "function" in code or "def " in code:
                    # Try to extract function name
                    func_match = re.search(r"(?:function|def)\s+(\w+)", code)
                    if func_match:
                        filename = f"{func_match.group(1).lower()}.{lang}"
                    else:
                        filename = f"{prefix}_function_{i+1}.{lang}"
                else:
                    filename = f"{prefix}_snippet_{i+1}.{lang}"
                
                file_path = os.path.join(output_dir, filename)
                with open(file_path, "w") as f:
                    f.write(code)
                logger.info(f"Saved code snippet: {file_path}")

class FileReaderTool(Tool):
    def run(self, input_data: str, context: Context) -> str:
        """Read a file and return its contents."""
        try:
            file_path = input_data
            if not os.path.exists(file_path):
                upload_dir = "uploads"
                file_path = os.path.join(upload_dir, input_data)
            
            if not os.path.exists(file_path):
                return f"Error: File not found: {input_data}"
            
            with open(file_path, 'r') as f:
                content = f.read()
            
            return f"File content of {file_path}:\n\n{content}"
        except Exception as e:
            return f"Error reading file: {str(e)}"

# === Agents ===
class OrchestratorAgent(Agent):
    def __init__(self, model):
        super().__init__(model)
        self.name = "orchestrator"
    
    def run(self, input_data: str, context: Context) -> str:
        logger.info(f"OrchestratorAgent processing: {input_data[:50]}...")
        context.store("user_prompt", input_data)
        
        clarified = self.model.generate("Clarify user prompt: " + input_data)
        context.store("clarified_prompt", clarified)
        
        logger.info(f"OrchestratorAgent completed clarification: {clarified[:50]}...")
        return clarified

class WorkflowDesignerAgent(Agent):
    def __init__(self, model):
        super().__init__(model)
        self.name = "workflow_designer"
    
    def run(self, input_data: str, context: Context) -> str:
        logger.info(f"WorkflowDesignerAgent processing: {input_data[:50]}...")
        
        # Check system resources to determine if parallel execution is possible
        system_monitor = get_monitor()
        can_run_parallel = system_monitor.can_run_parallel(2)  # Check if we can run 2 models in parallel
        
        # Generate workflow plan
        prompt = f"""Break down the following task into subtasks:
{input_data}

Consider the following:
1. The task should be broken down into logical components
2. Specify which agent should handle each subtask
3. Determine if subtasks can be executed in parallel or must be sequential
4. System can{'' if can_run_parallel else 'not'} run models in parallel based on current resources

Please format your response as a structured plan with clear steps and assignments.
"""
        workflow = self.model.generate(prompt)
        context.store("workflow_plan", workflow)
        
        logger.info(f"WorkflowDesignerAgent completed workflow design")
        return workflow

class CodeAgent(Agent):
    def __init__(self, model, name):
        super().__init__(model)
        self.name = name
    
    def run(self, input_data: str, context: Context) -> str:
        logger.info(f"{self.name.capitalize()}Agent processing task")
        
        # Get workflow plan and user prompt for context
        workflow_plan = context.retrieve("workflow_plan", "No workflow plan available")
        user_prompt = context.retrieve("user_prompt", "No user prompt available")
        clarified_prompt = context.retrieve("clarified_prompt", "No clarified prompt available")
        
        # Check if there are any uploaded files to consider
        uploaded_files = []
        if os.path.exists("uploads"):
            uploaded_files = os.listdir("uploads")
        
        # Generate code with proper context
        prompt = f"""As the {self.name} specialist, implement the code for this project.

User Request: {user_prompt}
Clarified Request: {clarified_prompt}
Workflow Plan: {workflow_plan}

{'Uploaded files to consider: ' + ', '.join(uploaded_files) if uploaded_files else 'No uploaded files to consider.'}

Please implement the {self.name} part of this project. Include:
1. Clear file structure
2. Well-commented code
3. Proper error handling
4. When writing code, use ```language\\n// filename: path/to/file.ext\\ncode...``` format to indicate where each file should be saved

Focus on creating production-quality, maintainable code.
"""
        result = self.model.generate(prompt)
        context.store(f"{self.name}_output", result)
        
        logger.info(f"{self.name.capitalize()}Agent completed implementation")
        return result

class ReviewerAgent(Agent):
    def __init__(self, model):
        super().__init__(model)
        self.name = "reviewer"
    
    def run(self, input_data: str, context: Context) -> str:
        logger.info("ReviewerAgent starting code review")
        
        # Get all outputs
        frontend_output = context.retrieve("frontend_output", "No frontend output available")
        backend_output = context.retrieve("backend_output", "No backend output available")
        workflow_plan = context.retrieve("workflow_plan", "No workflow plan available")
        user_prompt = context.retrieve("user_prompt", "No user prompt available")
        
        # Generate review
        prompt = f"""Review and improve the following code implementations:

User Request: {user_prompt}
Workflow Plan: {workflow_plan}

FRONTEND CODE:
{frontend_output}

BACKEND CODE:
{backend_output}

Please provide:
1. A comprehensive review of both implementations
2. Suggestions for improvements
3. Any identified bugs or issues
4. Improved code snippets where necessary (using ```language\\n// filename: path/to/file.ext\\ncode...``` format)
5. Ensure the frontend and backend integrate properly

Focus on code quality, security, performance, and maintainability.
"""
        review = self.model.generate(prompt)
        context.store("reviewed_output", review)
        
        logger.info("ReviewerAgent completed code review")
        return review

# === Model Initialization ===

# Initialize local model wrappers
main_model = LocalModelWrapper("llama2-main")
workflow_model = LocalModelWrapper("mistral-workflow")
coder_model1 = LocalModelWrapper("code-specialist-frontend")
coder_model2 = LocalModelWrapper("code-specialist-backend")
review_model = LocalModelWrapper("code-reviewer")

# Initialize agents
orchestrator = OrchestratorAgent(main_model)
workflow_designer = WorkflowDesignerAgent(workflow_model)
frontend_agent = CodeAgent(coder_model1, name="frontend")
backend_agent = CodeAgent(coder_model2, name="backend")
reviewer = ReviewerAgent(review_model)

# Initialize tools
saver = SaveOutputTool()
file_reader = FileReaderTool()

# === Define Workflow ===
def create_workflow(parallel_execution=True):
    """Create a workflow based on whether parallel execution is possible."""
    if parallel_execution:
        return Sequential([
            orchestrator,
            workflow_designer,
            Parallel([frontend_agent, backend_agent]),
            reviewer,
            saver
        ])
    else:
        return Sequential([
            orchestrator,
            workflow_designer,
            frontend_agent,
            backend_agent,
            reviewer,
            saver
        ])

# === Run Agent System ===
def run_agent_system(user_input: str) -> str:
    """Run the multi-agent system with the given user input."""
    # Create a new context
    context = Context()
    
    # Check system resources to determine execution strategy
    monitor = get_monitor()
    can_run_parallel = monitor.can_run_parallel(2)  # Check if we can run 2 models in parallel
    
    # Create workflow based on system capabilities
    multi_agent_workflow = create_workflow(parallel_execution=can_run_parallel)
    
    # Run the workflow
    logger.info(f"Starting multi-agent workflow with {'parallel' if can_run_parallel else 'sequential'} execution")
    output = multi_agent_workflow.run(user_input, context)
    logger.info("Multi-agent workflow completed")
    
    return output

if __name__ == "__main__":
    print("=== Multi-Agent System for Collaborative Coding ===")
    print("System is checking hardware capabilities...")
    
    # Check system resources
    monitor = get_monitor()
    system_info = monitor.get_system_info()
    current_usage = monitor.get_current_usage()
    
    print(f"\nSystem Information:")
    print(f"- CPU: {system_info['cpu_count']} logical cores ({system_info['physical_cpu_count']} physical)")
    print(f"- Memory: {system_info['total_memory_gb']} GB total")
    print(f"- Platform: {system_info['platform']}")
    if 'gpu_name' in system_info and system_info['gpu_name'] != "Not available":
        print(f"- GPU: {system_info['gpu_name']} with {system_info['gpu_memory_total_gb']} GB VRAM")
    
    print(f"\nCurrent Resource Usage:")
    print(f"- CPU: {current_usage['cpu']:.1f}%")
    print(f"- Memory: {current_usage['memory']:.1f}%")
    if current_usage.get('gpu_util') is not None:
        print(f"- GPU Utilization: {current_usage['gpu_util']:.1f}%")
        print(f"- GPU Memory: {current_usage['gpu_memory']:.1f}%")
    
    # Determine execution strategy
    can_run_parallel = monitor.can_run_parallel(2)
    print(f"\nExecution Strategy: {'Parallel' if can_run_parallel else 'Sequential'} execution")
    
    # Get user input
    user_prompt = input("\nEnter your coding task description: ")
    if not user_prompt:
        user_prompt = "Build a full-stack web app with authentication and a dashboard."
        print(f"Using default prompt: {user_prompt}")
    
    # Run the system
    print("\nRunning multi-agent system...")
    start_time = time.time()
    output = run_agent_system(user_prompt)
    end_time = time.time()
    
    print(f"\nTask completed in {end_time - start_time:.2f} seconds")
    print("Final Output:\n", output)
