import streamlit as st
import json
import time
import os
import threading
from datetime import datetime
from typing import Dict, List, Any, Optional

from my_models import LocalModelWrapper
from system_monitor import get_monitor
from adk.components import Agent, Sequential, Parallel, Loop, Tool
from adk.runtime import Context

# --- UI Setup ---

# Initialize session state variables
if 'conversation_history' not in st.session_state:
    st.session_state.conversation_history = []

if 'task_status' not in st.session_state:
    st.session_state.task_status = "Waiting for user input..."

if 'agent_states' not in st.session_state:
    st.session_state.agent_states = {
        "orchestrator": {"status": "idle", "progress": 0},
        "workflow_designer": {"status": "idle", "progress": 0},
        "frontend": {"status": "idle", "progress": 0},
        "backend": {"status": "idle", "progress": 0},
        "reviewer": {"status": "idle", "progress": 0}
    }

if 'current_workflow' not in st.session_state:
    st.session_state.current_workflow = None

if 'output_files' not in st.session_state:
    st.session_state.output_files = []

if 'system_resources' not in st.session_state:
    st.session_state.system_resources = {
        "cpu": 0,
        "memory": 0,
        "gpu_memory": 0,
        "gpu_util": 0
    }

# --- Tools ---

class SaveOutputTool(Tool):
    def run(self, input_data: str, context: Context) -> str:
        output_base_dir = "outputs"
        agent_logs_dir = os.path.join(output_base_dir, "agent_logs")
        src_dir = os.path.join(output_base_dir, "src")
        tests_dir = os.path.join(output_base_dir, "tests")

        os.makedirs(agent_logs_dir, exist_ok=True)
        os.makedirs(src_dir, exist_ok=True)
        os.makedirs(tests_dir, exist_ok=True)
        
        # Save agent logs
        for key in context.store_keys():
            if key.endswith("_output") or key in ["workflow_plan", "clarified_prompt"]:
                agent_name = key.replace("_output", "")
                log_path = os.path.join(agent_logs_dir, f"{agent_name}_log.txt")
                with open(log_path, "w") as f:
                    f.write(f"=== {agent_name.upper()} OUTPUT ===\n\n")
                    f.write(context.retrieve(key, f"No output for {agent_name}"))
                st.session_state.output_files.append(log_path)
        
        # Save final review
        final_output_log_path = os.path.join(agent_logs_dir, "final_processing_log.txt")
        with open(final_output_log_path, "w") as f:
            f.write("Reviewed Output/Final Summary:\n")
            f.write(context.retrieve("reviewed_output", "No reviewed output found."))
        st.session_state.output_files.append(final_output_log_path)
        
        # Create README.md
        readme_content = f"""# Project Output
## Generated by Multi-Agent System

**User Prompt:** {context.retrieve("user_prompt", "N/A")}
**Clarified Prompt:** {context.retrieve("clarified_prompt", "N/A")}

## Project Overview
{context.retrieve("workflow_plan", "No workflow plan available.")}

## Implementation Details
This project was generated by a collaborative multi-agent system with specialized agents:
- Orchestrator: Initial task understanding and clarification
- Workflow Designer: Task breakdown and planning
- Frontend Agent: UI and client-side implementation
- Backend Agent: Server-side and API implementation
- Reviewer: Code review and quality assurance

## Generated Files
- Source code: See the `src/` directory
- Tests: See the `tests/` directory
- Agent logs: See the `agent_logs/` directory

## Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""
        readme_path = os.path.join(output_base_dir, "README.md")
        with open(readme_path, "w") as f:
            f.write(readme_content)
        st.session_state.output_files.append(readme_path)

        # Create architecture.json
        architecture_data = {
            "description": "High-level architecture of the generated solution",
            "user_prompt": context.retrieve("user_prompt", "N/A"),
            "clarified_prompt": context.retrieve("clarified_prompt", "N/A"),
            "workflow_plan": context.retrieve("workflow_plan", "N/A"),
            "agents_involved": [
                "OrchestratorAgent",
                "WorkflowDesignerAgent",
                "FrontendCodeAgent",
                "BackendCodeAgent",
                "ReviewerAgent"
            ],
            "outputs": {
                "log_file": final_output_log_path,
                "readme": readme_path,
                "source_directory": src_dir,
                "tests_directory": tests_dir
            },
            "generation_timestamp": datetime.now().isoformat()
        }
        architecture_path = os.path.join(output_base_dir, "architecture.json")
        with open(architecture_path, "w") as f:
            json.dump(architecture_data, f, indent=4)
        st.session_state.output_files.append(architecture_path)

        # Extract and save code files from agent outputs
        self._extract_and_save_code_files(context, src_dir, tests_dir)
        
        return f"Outputs saved. Main log: {final_output_log_path}. See all files in '{output_base_dir}'."
    
    def _extract_and_save_code_files(self, context: Context, src_dir: str, tests_dir: str):
        """Extract code blocks from agent outputs and save them as files."""
        # Process frontend output
        frontend_output = context.retrieve("frontend_output", "")
        self._extract_code_blocks(frontend_output, src_dir, "frontend")
        
        # Process backend output
        backend_output = context.retrieve("backend_output", "")
        self._extract_code_blocks(backend_output, src_dir, "backend")
        
        # Process reviewer output (might contain improved code)
        reviewer_output = context.retrieve("reviewed_output", "")
        self._extract_code_blocks(reviewer_output, src_dir, "improved")
    
    def _extract_code_blocks(self, text: str, output_dir: str, prefix: str):
        """Extract code blocks from text and save them as files."""
        import re
        
        # Find code blocks with filename hints
        # Pattern matches: ```language\n// filename: path/to/file.ext\ncode...```
        pattern = r"```(?:\w+)?\s*\n(?://|#)\s*filename:\s*([^\n]+)\n(.*?)```"
        matches = re.finditer(pattern, text, re.DOTALL)
        
        for i, match in enumerate(matches):
            filename = match.group(1).strip()
            code = match.group(2).strip()
            
            # Create subdirectories if needed
            file_path = os.path.join(output_dir, filename)
            os.makedirs(os.path.dirname(file_path), exist_ok=True)
            
            with open(file_path, "w") as f:
                f.write(code)
            st.session_state.output_files.append(file_path)
        
        # If no filename hints were found, look for regular code blocks
        if i == 0:
            pattern = r"```(\w+)?\n(.*?)```"
            matches = re.finditer(pattern, text, re.DOTALL)
            
            for i, match in enumerate(matches):
                lang = match.group(1) or "txt"
                code = match.group(2).strip()
                
                # Generate a filename based on content or use a default
                if "class" in code and lang in ["python", "py"]:
                    # Try to extract class name
                    class_match = re.search(r"class\s+(\w+)", code)
                    if class_match:
                        filename = f"{class_match.group(1).lower()}.{lang}"
                    else:
                        filename = f"{prefix}_code_{i+1}.{lang}"
                elif "function" in code or "def " in code:
                    # Try to extract function name
                    func_match = re.search(r"(?:function|def)\s+(\w+)", code)
                    if func_match:
                        filename = f"{func_match.group(1).lower()}.{lang}"
                    else:
                        filename = f"{prefix}_function_{i+1}.{lang}"
                else:
                    filename = f"{prefix}_snippet_{i+1}.{lang}"
                
                file_path = os.path.join(output_dir, filename)
                with open(file_path, "w") as f:
                    f.write(code)
                st.session_state.output_files.append(file_path)

class FileReaderTool(Tool):
    def run(self, input_data: str, context: Context) -> str:
        """Read a file and return its contents."""
        try:
            file_path = input_data
            if not os.path.exists(file_path):
                upload_dir = "uploads"
                file_path = os.path.join(upload_dir, input_data)
            
            if not os.path.exists(file_path):
                return f"Error: File not found: {input_data}"
            
            with open(file_path, 'r') as f:
                content = f.read()
            
            return f"File content of {file_path}:\n\n{content}"
        except Exception as e:
            return f"Error reading file: {str(e)}"

# --- Agents ---

class OrchestratorAgent(Agent):
    def __init__(self, model):
        super().__init__(model)
        self.name = "orchestrator"
    
    def run(self, input_data: str, context: Context) -> str:
        update_agent_state(self.name, "active", 25)
        context.store("user_prompt", input_data)
        
        # Add a message to the conversation
        update_conversation(self.name, "I'm analyzing your request and clarifying the requirements...")
        
        clarified = self.model.generate("Clarify user prompt: " + input_data)
        context.store("clarified_prompt", clarified)
        
        update_agent_state(self.name, "completed", 100)
        update_conversation(self.name, f"I've clarified your request: {clarified}")
        
        return clarified

class WorkflowDesignerAgent(Agent):
    def __init__(self, model):
        super().__init__(model)
        self.name = "workflow_designer"
    
    def run(self, input_data: str, context: Context) -> str:
        update_agent_state(self.name, "active", 25)
        
        # Add a message to the conversation
        update_conversation(self.name, "I'm breaking down the task into subtasks and designing the workflow...")
        
        # Check system resources to determine if parallel execution is possible
        system_monitor = get_monitor()
        can_run_parallel = system_monitor.can_run_parallel(2)  # Check if we can run 2 models in parallel
        
        # Generate workflow plan
        prompt = f"""Break down the following task into subtasks:
{input_data}

Consider the following:
1. The task should be broken down into logical components
2. Specify which agent should handle each subtask
3. Determine if subtasks can be executed in parallel or must be sequential
4. System can{'' if can_run_parallel else 'not'} run models in parallel based on current resources

Please format your response as a structured plan with clear steps and assignments.
"""
        workflow = self.model.generate(prompt)
        context.store("workflow_plan", workflow)
        
        update_agent_state(self.name, "completed", 100)
        update_conversation(self.name, "I've designed the workflow plan. Here's how we'll approach this:")
        update_conversation(self.name, workflow)
        
        return workflow

class CodeAgent(Agent):
    def __init__(self, model, name):
        super().__init__(model)
        self.name = name
    
    def run(self, input_data: str, context: Context) -> str:
        update_agent_state(self.name, "active", 25)
        
        # Get workflow plan and user prompt for context
        workflow_plan = context.retrieve("workflow_plan", "No workflow plan available")
        user_prompt = context.retrieve("user_prompt", "No user prompt available")
        clarified_prompt = context.retrieve("clarified_prompt", "No clarified prompt available")
        
        # Check if there are any uploaded files to consider
        uploaded_files = []
        if os.path.exists("uploads"):
            uploaded_files = os.listdir("uploads")
        
        # Add a message to the conversation
        update_conversation(self.name, f"I'm working on the {self.name} implementation...")
        
        # Generate code with proper context
        prompt = f"""As the {self.name} specialist, implement the code for this project.

User Request: {user_prompt}
Clarified Request: {clarified_prompt}
Workflow Plan: {workflow_plan}

{'Uploaded files to consider: ' + ', '.join(uploaded_files) if uploaded_files else 'No uploaded files to consider.'}

Please implement the {self.name} part of this project. Include:
1. Clear file structure
2. Well-commented code
3. Proper error handling
4. When writing code, use ```language\\n// filename: path/to/file.ext\\ncode...``` format to indicate where each file should be saved

Focus on creating production-quality, maintainable code.
"""
        # Simulate progress
        update_agent_state(self.name, "active", 50)
        time.sleep(0.5)  # Simulate thinking time
        
        result = self.model.generate(prompt)
        context.store(f"{self.name}_output", result)
        
        update_agent_state(self.name, "completed", 100)
        update_conversation(self.name, f"I've completed the {self.name} implementation.")
        
        return result

class ReviewerAgent(Agent):
    def __init__(self, model):
        super().__init__(model)
        self.name = "reviewer"
    
    def run(self, input_data: str, context: Context) -> str:
        update_agent_state(self.name, "active", 25)
        
        # Add a message to the conversation
        update_conversation(self.name, "I'm reviewing the code from all agents and suggesting improvements...")
        
        # Get all outputs
        frontend_output = context.retrieve("frontend_output", "No frontend output available")
        backend_output = context.retrieve("backend_output", "No backend output available")
        workflow_plan = context.retrieve("workflow_plan", "No workflow plan available")
        user_prompt = context.retrieve("user_prompt", "No user prompt available")
        
        # Simulate progress
        update_agent_state(self.name, "active", 50)
        time.sleep(0.5)  # Simulate thinking time
        
        # Generate review
        prompt = f"""Review and improve the following code implementations:

User Request: {user_prompt}
Workflow Plan: {workflow_plan}

FRONTEND CODE:
{frontend_output}

BACKEND CODE:
{backend_output}

Please provide:
1. A comprehensive review of both implementations
2. Suggestions for improvements
3. Any identified bugs or issues
4. Improved code snippets where necessary (using ```language\\n// filename: path/to/file.ext\\ncode...``` format)
5. Ensure the frontend and backend integrate properly

Focus on code quality, security, performance, and maintainability.
"""
        review = self.model.generate(prompt)
        context.store("reviewed_output", review)
        
        update_agent_state(self.name, "completed", 100)
        update_conversation(self.name, "I've completed my review. Here are my findings and improvements:")
        update_conversation(self.name, review[:500] + "..." if len(review) > 500 else review)
        
        return review

# --- Model Initialization ---

# Initialize local model wrappers
main_model = LocalModelWrapper("llama2-main")
workflow_model = LocalModelWrapper("mistral-workflow")
coder_model1 = LocalModelWrapper("code-specialist-frontend")
coder_model2 = LocalModelWrapper("code-specialist-backend")
review_model = LocalModelWrapper("code-reviewer")

# Initialize agents
orchestrator = OrchestratorAgent(main_model)
workflow_designer = WorkflowDesignerAgent(workflow_model)
frontend_agent = CodeAgent(coder_model1, name="frontend")
backend_agent = CodeAgent(coder_model2, name="backend")
reviewer = ReviewerAgent(review_model)

# Initialize tools
saver = SaveOutputTool()
file_reader = FileReaderTool()

# --- Helper Functions ---

def update_agent_state(agent_name: str, status: str, progress: int):
    """Update the state of an agent in the session state."""
    if agent_name in st.session_state.agent_states:
        st.session_state.agent_states[agent_name]["status"] = status
        st.session_state.agent_states[agent_name]["progress"] = progress

def update_conversation(agent_name: str, message: str):
    """Add a message to the conversation history."""
    timestamp = datetime.now().strftime("%H:%M:%S")
    st.session_state.conversation_history.append({
        "agent": agent_name,
        "message": message,
        "timestamp": timestamp
    })
    st.session_state.task_status = f"{agent_name.capitalize()} is working on it..."

def update_system_resources():
    """Update system resource information in the session state."""
    monitor = get_monitor()
    resources = monitor.get_current_usage()
    st.session_state.system_resources = resources

def run_agent_system(user_input: str) -> str:
    """Run the multi-agent system with the given user input."""
    # Reset agent states
    for agent in st.session_state.agent_states:
        st.session_state.agent_states[agent] = {"status": "idle", "progress": 0}
    
    # Create a new context
    context = Context()
    
    # Check system resources to determine execution strategy
    monitor = get_monitor()
    can_run_parallel = monitor.can_run_parallel(2)  # Check if we can run 2 models in parallel
    
    # Define the workflow based on system capabilities
    if can_run_parallel:
        multi_agent_workflow = Sequential([
            orchestrator,
            workflow_designer,
            Parallel([frontend_agent, backend_agent]),
            reviewer,
            saver
        ])
        st.session_state.current_workflow = "parallel"
    else:
        multi_agent_workflow = Sequential([
            orchestrator,
            workflow_designer,
            frontend_agent,
            backend_agent,
            reviewer,
            saver
        ])
        st.session_state.current_workflow = "sequential"
    
    # Run the workflow
    output = multi_agent_workflow.run(user_input, context)
    
    # Update task status
    st.session_state.task_status = "Task completed!"
    
    return output

# --- Background Tasks ---

def start_resource_monitoring():
    """Start a background thread to update system resources periodically."""
    def update_resources_periodically():
        while True:
            update_system_resources()
            time.sleep(2)  # Update every 2 seconds
    
    thread = threading.Thread(target=update_resources_periodically, daemon=True)
    thread.start()

# Start resource monitoring when the app loads
start_resource_monitoring()

# --- Streamlit UI Layout ---

st.set_page_config(
    page_title="Multi-Agent Coding Assistant",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Main title
st.title("🤖 Multi-Agent Coding Assistant")
st.markdown("*Powered by Google ADK and Local LLMs*")

# Create a two-column layout
col1, col2 = st.columns([2, 1])

with col1:
    # User input section
    st.subheader("📝 Task Description")
    user_prompt = st.text_area("Describe your coding task in detail", height=100)
    
    # File upload section
    st.subheader("📎 Upload Files/Images")
    uploaded_file = st.file_uploader("Upload reference files, code, or images", 
                                    type=["txt", "py", "js", "html", "css", "json", "jpg", "png", "pdf"])
    
    if uploaded_file is not None:
        upload_dir = "uploads"
        os.makedirs(upload_dir, exist_ok=True)
        
        file_path = os.path.join(upload_dir, uploaded_file.name)
        with open(file_path, "wb") as f:
            f.write(uploaded_file.getbuffer())
        
        st.success(f"Uploaded: {uploaded_file.name}")
        
        # Display image preview if it's an image
        if uploaded_file.type.startswith('image'):
            st.image(uploaded_file, caption=uploaded_file.name, width=300)
    
    # Submit button
    submit_col1, submit_col2 = st.columns([1, 3])
    with submit_col1:
        submit_button = st.button("🚀 Submit Task", use_container_width=True)
    
    # Conversation history
    st.subheader("💬 Agent Conversation")
    conversation_container = st.container(height=400)
    
    with conversation_container:
        for msg in st.session_state.conversation_history:
            agent = msg["agent"]
            message = msg["message"]
            timestamp = msg["timestamp"]
            
            # Style the message based on the agent
            if agent == "User":
                st.markdown(f"**👤 You ({timestamp}):**")
                st.markdown(f"> {message}")
            else:
                agent_icons = {
                    "orchestrator": "🎯",
                    "workflow_designer": "🔄",
                    "frontend": "🖥️",
                    "backend": "⚙️",
                    "reviewer": "🔍"
                }
                icon = agent_icons.get(agent, "🤖")
                st.markdown(f"**{icon} {agent.capitalize()} ({timestamp}):**")
                st.markdown(f"{message}")
            
            st.markdown("---")

with col2:
    # System status
    st.subheader("⚙️ System Status")
    
    # Display current workflow type
    if st.session_state.current_workflow:
        workflow_type = st.session_state.current_workflow.capitalize()
        st.info(f"Current execution mode: {workflow_type}")
    
    # Display system resources
    resources = st.session_state.system_resources
    
    # CPU and Memory usage
    cpu_col, mem_col = st.columns(2)
    with cpu_col:
        st.metric("CPU Usage", f"{resources['cpu']:.1f}%")
    with mem_col:
        st.metric("Memory Usage", f"{resources['memory']:.1f}%")
    
    # GPU usage if available
    if resources.get('gpu_util') is not None and resources.get('gpu_memory') is not None:
        gpu_util_col, gpu_mem_col = st.columns(2)
        with gpu_util_col:
            st.metric("GPU Util", f"{resources['gpu_util']:.1f}%")
        with gpu_mem_col:
            st.metric("GPU Memory", f"{resources['gpu_memory']:.1f}%")
    
    # Agent status
    st.subheader("🤖 Agent Status")
    
    for agent, state in st.session_state.agent_states.items():
        status = state["status"]
        progress = state["progress"]
        
        # Display status with color coding
        if status == "idle":
            st.text(f"{agent.capitalize()}: Waiting")
        elif status == "active":
            st.text(f"{agent.capitalize()}: Working")
            st.progress(progress)
        elif status == "completed":
            st.text(f"{agent.capitalize()}: Completed")
            st.progress(100)
    
    # Output files
    if st.session_state.output_files:
        st.subheader("📁 Generated Files")
        for file_path in st.session_state.output_files:
            file_name = os.path.basename(file_path)
            st.text(file_name)

# Handle form submission
if submit_button and user_prompt:
    # Update conversation with user input
    update_conversation("User", user_prompt)
    
    # Run the agent system with the user input
    with st.spinner("Multi-agent system is processing your request..."):
        result = run_agent_system(user_prompt)
    
    # Display the result
    st.success("Task completed successfully!")
    
    # Show output directory
    st.subheader("📂 Output Directory")
    st.markdown(f"All generated files are saved in the `outputs` directory.")
    
    # Add a download button for the output
    if os.path.exists("outputs/README.md"):
        with open("outputs/README.md", "r") as f:
            readme_content = f.read()
        st.download_button(
            label="Download README",
            data=readme_content,
            file_name="README.md",
            mime="text/markdown"
        )
